apiVersion: v1
kind: Deployment
metadata:
  name: flex-kv
spec:
  containers:
  - name: flex-kv
    image: registryzlh9820.azurecr.io/tripinsights/flex-kv:1.0
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: kvcreds
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: kvcreds2
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds2                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds2    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: kvcreds3
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds3                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds3    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: kvcreds4
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds4                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds4    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: kvcreds5
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds5                 # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds5    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: kvcreds6
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds6                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: kvcreds6    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
  - name: sql-user
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: sql-user                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "MSHackVault"               # the name of the KeyVault
        keyvaultobjectnames: sql-user    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "openhack-containers"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "1b6a0f9d-fe70-4fb5-ae24-5b615270aebe"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "1b81d454-d1ab-4c0b-9c98-9f7eb8a03a59"                   # the tenant ID of the KeyVault
