apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
      matchLabels:
        app: tripviewer
  replicas: 1
  template:
      metadata:
        labels:
            app: tripviewer
      spec:
        containers:
        - name: tripviewer
          image: registryzlh9820.azurecr.io/tripinsights/tripviewer:1.0
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"  
          - name: USERPROFILE_API_ENDPOINT
            value: "http://10.0.85.53:80"
          - name: TRIPS_API_ENDPOINT
            value: "http://13.82.19.78:80"
          - name: BING_MAPS_KEY
            value: ""
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: ingress-basic
spec:
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer