apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /api($1)
spec:
  rules:
  - http:
      paths:
      - path: /api/poi/
        backend:
          serviceName: poi
          servicePort: 80
      - path: /api/trips
        backend:
          serviceName: trips
          servicePort: 80
      - path: /api/user-java/healthcheck
        backend:
          serviceName: user-java
          servicePort: 80
      - path: api/user
        backend:
          serviceName: userprofile
          servicePort: 80
      