apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tripviewer
          servicePort: 80
      