apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: ingress-basic
spec:
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer