apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  selector:
      matchLabels:
        app: trips
  replicas: 1
  template:
      metadata:
        labels:
            app: trips
      spec:
        containers:
        - name: trips
          image: registryzlh9820.azurecr.io/tripinsights/trips:1.0
          env:
          - name: SQL_SERVER
            value:  "sqlserverzlh9820.database.windows.net"
          - name: SQL_DB
            value: "mydrivingDB"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientid
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientsecret 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: OPENAPI_DOCS_URI
            value: "http://13.82.19.78:8081"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP