apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  selector:
      matchLabels:
        app: poi
  replicas: 1
  template:
      metadata:
        labels:
            app: poi
      spec:
        containers:
        - name: poi
          image: registryzlh9820.azurecr.io/tripinsights/poi:1.0
          env:
          - name: SQL_SERVER
            value:  "sqlserverzlh9820.database.windows.net"
          - name: SQL_DB
            value: "mydrivingDB"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"  
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientid
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientsecret      
          ports:
          - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP