apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector:
      matchLabels:
        app: userprofile
  replicas: 1
  template:
      metadata:
        labels:
            app: userprofile
      spec:
        containers:
        - name: userprofile
          image: registryzlh9820.azurecr.io/tripinsights/userprofile:1.0
          env:
          - name: SQL_SERVER
            value:  "sqlserverzlh9820.database.windows.net"
          - name: SQL_DB
            value: "mydrivingDB"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientid
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: clientsecret             
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"  
          ports:
          - containerPort: 80
          
